version: '3.8'

services:
  studio:
    build: .
    container_name: live-studio-pro
    ports:
      - "3000:3000"
    volumes:
      - ./public/records:/usr/src/app/public/records
      - ./public/fonts:/usr/src/app/public/fonts
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
